# -*- coding: utf-8 -*-

import hc_coding
import hc_value_set_contains
import hc_odoo_base
import hc_element
import hc_period
import hc_telecom
import hc_address
import hc_annotation
import hc_attachment
import hc_available_time
import hc_timing
import hc_dosage
import hc_human_name
import hc_identifier
import hc_language
import hc_meta
import hc_narrative
import hc_organization_name
import hc_quantity
import hc_range
import hc_ratio
import hc_related_resource
import hc_reference
import hc_resource
import hc_sampled_data
import hc_signature
import product_uom
import hc_extension
import hc_backbone_element
import hc_domain_resource
import hc_element_definition
import hc_value_set_contains_v3
import hc_element_extension
